/**
 * DS-01 / THEME-01 — the theme colour maps as data.
 *
 * `app/styles/tokens.css` is the authoritative SOURCE of every token value; this
 * module mirrors each theme's COLOUR map as plain data so tests can reason about
 * them: completeness and parity against the CSS (every theme must define the same
 * names with the same values) and WCAG contrast of the critical pairs, in every
 * theme. A sync test (`test/unit/tokens/tokens.test.ts`) fails if this drifts from
 * the CSS, so the two can never disagree.
 *
 * Keys are the semantic token names WITHOUT the `--dh-color-` prefix; values are
 * the literal colour strings used in that theme.
 */

/** The semantic colour token names (without the `--dh-color-` prefix). */
export const COLOR_TOKEN_NAMES = [
  "bg",
  "surface",
  "surface-raised",
  "surface-sunken",
  "surface-nav",
  "surface-header",
  "surface-card",
  "text",
  "text-secondary",
  "text-muted",
  "on-accent",
  "link",
  "link-hover",
  "border",
  "border-strong",
  "border-subtle",
  "control-border",
  "divider",
  "accent",
  "accent-hover",
  "accent-active",
  "accent-text",
  "accent-surface",
  "secondary",
  "secondary-hover",
  "success",
  "success-surface",
  "success-text",
  "warning",
  "warning-surface",
  "warning-text",
  "danger",
  "danger-surface",
  "danger-text",
  "info",
  "info-surface",
  "info-text",
  "hover-surface",
  "active-surface",
  "disabled-surface",
  "disabled-text",
  "disabled-border",
  "focus-ring",
  "selection-bg",
  "selection-text",
  "overlay",
  "priority-p1",
  "priority-p1-surface",
  "priority-p1-text",
  "priority-p2",
  "priority-p2-surface",
  "priority-p2-text",
  "priority-p3",
  "priority-p3-surface",
  "priority-p3-text",
  "priority-p4",
  "priority-p4-surface",
  "priority-p4-text",
  "state-overdue",
  "state-overdue-surface",
  "state-overdue-text",
  "state-due-soon",
  "state-due-soon-surface",
  "state-due-soon-text",
  "state-completed",
  "state-completed-surface",
  "state-completed-text",
  "state-waiting",
  "state-waiting-surface",
  "state-waiting-text",
  "state-on-hold",
  "state-on-hold-surface",
  "state-on-hold-text",
  "progress-track",
  "progress-fill",
  "progress-complete",
  "chart-1",
  "chart-2",
  "chart-3",
  "chart-4",
  "chart-5",
  "chart-6",
  "skeleton-base",
  "skeleton-highlight",
] as const;

/** A semantic colour token name. */
export type ColorTokenName = (typeof COLOR_TOKEN_NAMES)[number];

/** A complete colour map: every semantic colour token to a concrete value. */
export type ColorMap = Readonly<Record<ColorTokenName, string>>;

/** The entity types that carry an identity accent (PX-02). */
export const ENTITY_ACCENT_NAMES = [
  "area",
  "goal",
  "project",
  "task",
  "note",
  "meeting",
  "person",
  "asset",
  "diary",
  "review",
] as const;

/** An entity-identity accent name. */
export type EntityAccentName = (typeof ENTITY_ACCENT_NAMES)[number];

/** A complete entity-accent map for one theme. */
export type EntityAccentMap = Readonly<Record<EntityAccentName, string>>;

/** Daly Light — the default theme. Mirrors the `:root` map in tokens.css. */
export const dalyLightTheme: ColorMap = {
  bg: "#faf9f7",
  surface: "#f2f1ed",
  "surface-raised": "#ffffff",
  "surface-sunken": "#eae8e3",
  "surface-nav": "#f5f4f0",
  "surface-header": "#fbfaf8",
  "surface-card": "#ffffff",
  text: "#1c1e22",
  "text-secondary": "#474c55",
  "text-muted": "#5b616b",
  "on-accent": "#ffffff",
  link: "#14606c",
  "link-hover": "#0e4a54",
  border: "#dedcd6",
  "border-strong": "#c2bfb7",
  "border-subtle": "#ebe9e4",
  "control-border": "#83817b",
  divider: "#e6e4de",
  accent: "#176b78",
  "accent-hover": "#135a65",
  "accent-active": "#0e4a54",
  "accent-text": "#14606c",
  "accent-surface": "#e2f0f2",
  secondary: "#eceae5",
  "secondary-hover": "#e2dfd8",
  success: "#1f7a44",
  "success-surface": "#e4f2ea",
  "success-text": "#186036",
  warning: "#9a6300",
  "warning-surface": "#f8ecd8",
  "warning-text": "#7a4f00",
  danger: "#c02f24",
  "danger-surface": "#fae7e5",
  "danger-text": "#9f261d",
  info: "#1c6b95",
  "info-surface": "#e2eff7",
  "info-text": "#155677",
  "hover-surface": "#efede8",
  "active-surface": "#e5e2dc",
  "disabled-surface": "#efede8",
  "disabled-text": "#8d8f92",
  "disabled-border": "#e2e0da",
  "focus-ring": "#176b78",
  "selection-bg": "#c9e6ea",
  "selection-text": "#0d2c31",
  overlay: "rgba(28, 26, 22, 0.48)",
  "priority-p1": "#c02f24",
  "priority-p1-surface": "#fae7e5",
  "priority-p1-text": "#9f261d",
  "priority-p2": "#9a6300",
  "priority-p2-surface": "#f8ecd8",
  "priority-p2-text": "#7a4f00",
  "priority-p3": "#1c6b95",
  "priority-p3-surface": "#e2eff7",
  "priority-p3-text": "#155677",
  "priority-p4": "#6b7078",
  "priority-p4-surface": "#eeece7",
  "priority-p4-text": "#565b63",
  "state-overdue": "#c02f24",
  "state-overdue-surface": "#fae7e5",
  "state-overdue-text": "#9f261d",
  "state-due-soon": "#9a6300",
  "state-due-soon-surface": "#f8ecd8",
  "state-due-soon-text": "#7a4f00",
  "state-completed": "#1f7a44",
  "state-completed-surface": "#e4f2ea",
  "state-completed-text": "#186036",
  "state-waiting": "#6d5aa8",
  "state-waiting-surface": "#ece8f6",
  "state-waiting-text": "#564488",
  "state-on-hold": "#6b7078",
  "state-on-hold-surface": "#eeece7",
  "state-on-hold-text": "#565b63",
  "progress-track": "#e5e2dc",
  "progress-fill": "#176b78",
  "progress-complete": "#1f7a44",
  "chart-1": "#176b78",
  "chart-2": "#9a6300",
  "chart-3": "#6d5aa8",
  "chart-4": "#1f7a44",
  "chart-5": "#b0512c",
  "chart-6": "#1c6b95",
  "skeleton-base": "#eae8e3",
  "skeleton-highlight": "#f6f5f2",
};

/** Daly Dark. Mirrors BOTH dark blocks in tokens.css (a parity test keeps them identical). */
export const dalyDarkTheme: ColorMap = {
  bg: "#101215",
  surface: "#171a1f",
  "surface-raised": "#1e222a",
  "surface-sunken": "#0a0c0f",
  "surface-nav": "#13161a",
  "surface-header": "#13161a",
  "surface-card": "#181c22",
  text: "#eef0f3",
  "text-secondary": "#c2c8d1",
  "text-muted": "#949ba7",
  "on-accent": "#ffffff",
  link: "#6fc7d2",
  "link-hover": "#8ed7e0",
  border: "#2a2f37",
  "border-strong": "#3b414b",
  "border-subtle": "#20242b",
  "control-border": "#6f7683",
  divider: "#22262d",
  accent: "#2a7581",
  "accent-hover": "#2d7d8a",
  "accent-active": "#2e808d",
  "accent-text": "#6fc7d2",
  "accent-surface": "#12262a",
  secondary: "#222730",
  "secondary-hover": "#2b3039",
  success: "#2f9c5c",
  "success-surface": "#0f2419",
  "success-text": "#5cd18e",
  warning: "#c98c33",
  "warning-surface": "#241a0c",
  "warning-text": "#e5b25b",
  danger: "#d9534a",
  "danger-surface": "#291211",
  "danger-text": "#f2958c",
  info: "#3a8fce",
  "info-surface": "#0d1e2b",
  "info-text": "#6fb8e6",
  "hover-surface": "#1c2027",
  "active-surface": "#242932",
  "disabled-surface": "#181c22",
  "disabled-text": "#646a76",
  "disabled-border": "#252a32",
  "focus-ring": "#6fc7d2",
  "selection-bg": "#1e4a52",
  "selection-text": "#e6f6f8",
  overlay: "rgba(0, 0, 0, 0.62)",
  "priority-p1": "#d9534a",
  "priority-p1-surface": "#291211",
  "priority-p1-text": "#f2958c",
  "priority-p2": "#c98c33",
  "priority-p2-surface": "#241a0c",
  "priority-p2-text": "#e5b25b",
  "priority-p3": "#3a8fce",
  "priority-p3-surface": "#0d1e2b",
  "priority-p3-text": "#6fb8e6",
  "priority-p4": "#7b8290",
  "priority-p4-surface": "#1c2027",
  "priority-p4-text": "#a3aab6",
  "state-overdue": "#d9534a",
  "state-overdue-surface": "#291211",
  "state-overdue-text": "#f2958c",
  "state-due-soon": "#c98c33",
  "state-due-soon-surface": "#241a0c",
  "state-due-soon-text": "#e5b25b",
  "state-completed": "#2f9c5c",
  "state-completed-surface": "#0f2419",
  "state-completed-text": "#5cd18e",
  "state-waiting": "#8b7ad4",
  "state-waiting-surface": "#191630",
  "state-waiting-text": "#b3a6f0",
  "state-on-hold": "#7b8290",
  "state-on-hold-surface": "#1c2027",
  "state-on-hold-text": "#a3aab6",
  "progress-track": "#242932",
  "progress-fill": "#4fb3bf",
  "progress-complete": "#2f9c5c",
  "chart-1": "#4fb3bf",
  "chart-2": "#d9a24a",
  "chart-3": "#a08ae6",
  "chart-4": "#4fbb7c",
  "chart-5": "#e07a53",
  "chart-6": "#5aa5dd",
  "skeleton-base": "#1c2027",
  "skeleton-highlight": "#262b33",
};

/** Eucalypt. Mirrors the `eucalypt` theme block in tokens.css. */
export const eucalyptTheme: ColorMap = {
  bg: "#f7f5ef",
  surface: "#eeebe1",
  "surface-raised": "#fdfcf8",
  "surface-sunken": "#e5e1d4",
  "surface-nav": "#f1eee5",
  "surface-header": "#f8f6f1",
  "surface-card": "#fdfcf8",
  text: "#22261f",
  "text-secondary": "#4a5045",
  "text-muted": "#5d6454",
  "on-accent": "#ffffff",
  link: "#3a6242",
  "link-hover": "#2b4d31",
  border: "#dbd6c7",
  "border-strong": "#bdb7a4",
  "border-subtle": "#e8e4d9",
  "control-border": "#85826f",
  divider: "#e2ded1",
  accent: "#3f6b47",
  "accent-hover": "#355c3c",
  "accent-active": "#2b4d31",
  "accent-text": "#3a6242",
  "accent-surface": "#e1ebdc",
  secondary: "#e9e5d9",
  "secondary-hover": "#ded9ca",
  success: "#2f7040",
  "success-surface": "#e2eedd",
  "success-text": "#255832",
  warning: "#8f6108",
  "warning-surface": "#f4ead2",
  "warning-text": "#714d06",
  danger: "#a83a2b",
  "danger-surface": "#f5e3de",
  "danger-text": "#8a3023",
  info: "#2b6474",
  "info-surface": "#e0edf0",
  "info-text": "#22505d",
  "hover-surface": "#ece8dd",
  "active-surface": "#e2ded1",
  "disabled-surface": "#eceadf",
  "disabled-text": "#8b8b7f",
  "disabled-border": "#e0dccf",
  "focus-ring": "#3f6b47",
  "selection-bg": "#cfe0c9",
  "selection-text": "#1d2c1e",
  overlay: "rgba(32, 34, 26, 0.48)",
  "priority-p1": "#a83a2b",
  "priority-p1-surface": "#f5e3de",
  "priority-p1-text": "#8a3023",
  "priority-p2": "#8f6108",
  "priority-p2-surface": "#f4ead2",
  "priority-p2-text": "#714d06",
  "priority-p3": "#2b6474",
  "priority-p3-surface": "#e0edf0",
  "priority-p3-text": "#22505d",
  "priority-p4": "#6b7061",
  "priority-p4-surface": "#eae7dc",
  "priority-p4-text": "#565b4e",
  "state-overdue": "#a83a2b",
  "state-overdue-surface": "#f5e3de",
  "state-overdue-text": "#8a3023",
  "state-due-soon": "#8f6108",
  "state-due-soon-surface": "#f4ead2",
  "state-due-soon-text": "#714d06",
  "state-completed": "#2f7040",
  "state-completed-surface": "#e2eedd",
  "state-completed-text": "#255832",
  "state-waiting": "#5f5a94",
  "state-waiting-surface": "#e6e4f0",
  "state-waiting-text": "#4b4776",
  "state-on-hold": "#6b7061",
  "state-on-hold-surface": "#eae7dc",
  "state-on-hold-text": "#565b4e",
  "progress-track": "#ded9ca",
  "progress-fill": "#3f6b47",
  "progress-complete": "#2f7040",
  "chart-1": "#3f6b47",
  "chart-2": "#8f6108",
  "chart-3": "#5f5a94",
  "chart-4": "#2b6474",
  "chart-5": "#a05437",
  "chart-6": "#6b7061",
  "skeleton-base": "#e5e1d4",
  "skeleton-highlight": "#f3f0e7",
};

/** Coastal. Mirrors the `coastal` theme block in tokens.css. */
export const coastalTheme: ColorMap = {
  bg: "#f4f7f9",
  surface: "#e8eef2",
  "surface-raised": "#ffffff",
  "surface-sunken": "#dce5eb",
  "surface-nav": "#eef3f6",
  "surface-header": "#f6f9fa",
  "surface-card": "#ffffff",
  text: "#16232b",
  "text-secondary": "#3e4f5b",
  "text-muted": "#53636e",
  "on-accent": "#ffffff",
  link: "#175f7d",
  "link-hover": "#124a62",
  border: "#d3dee5",
  "border-strong": "#b3c2cc",
  "border-subtle": "#e2eaef",
  "control-border": "#76848e",
  divider: "#dde6ec",
  accent: "#1c6b8c",
  "accent-hover": "#175a77",
  "accent-active": "#124a62",
  "accent-text": "#175f7d",
  "accent-surface": "#dbeaf2",
  secondary: "#e4ebf0",
  "secondary-hover": "#d8e2e9",
  success: "#1c7554",
  "success-surface": "#dcefe6",
  "success-text": "#155c42",
  warning: "#8d6205",
  "warning-surface": "#f4ecd6",
  "warning-text": "#6f4d04",
  danger: "#b93a35",
  "danger-surface": "#f8e5e4",
  "danger-text": "#98302b",
  info: "#1f6b9e",
  "info-surface": "#dfedf7",
  "info-text": "#18567e",
  "hover-surface": "#e7edf1",
  "active-surface": "#dbe4ea",
  "disabled-surface": "#e9eef1",
  "disabled-text": "#82909a",
  "disabled-border": "#dce4e9",
  "focus-ring": "#1c6b8c",
  "selection-bg": "#c4dfec",
  "selection-text": "#0e2833",
  overlay: "rgba(16, 28, 36, 0.48)",
  "priority-p1": "#b93a35",
  "priority-p1-surface": "#f8e5e4",
  "priority-p1-text": "#98302b",
  "priority-p2": "#8d6205",
  "priority-p2-surface": "#f4ecd6",
  "priority-p2-text": "#6f4d04",
  "priority-p3": "#1f6b9e",
  "priority-p3-surface": "#dfedf7",
  "priority-p3-text": "#18567e",
  "priority-p4": "#657682",
  "priority-p4-surface": "#e6ecf0",
  "priority-p4-text": "#526069",
  "state-overdue": "#b93a35",
  "state-overdue-surface": "#f8e5e4",
  "state-overdue-text": "#98302b",
  "state-due-soon": "#8d6205",
  "state-due-soon-surface": "#f4ecd6",
  "state-due-soon-text": "#6f4d04",
  "state-completed": "#1c7554",
  "state-completed-surface": "#dcefe6",
  "state-completed-text": "#155c42",
  "state-waiting": "#5f5da3",
  "state-waiting-surface": "#e5e6f4",
  "state-waiting-text": "#4b4a82",
  "state-on-hold": "#657682",
  "state-on-hold-surface": "#e6ecf0",
  "state-on-hold-text": "#526069",
  "progress-track": "#d8e2e9",
  "progress-fill": "#1c6b8c",
  "progress-complete": "#1c7554",
  "chart-1": "#1c6b8c",
  "chart-2": "#1c7554",
  "chart-3": "#5f5da3",
  "chart-4": "#8d6205",
  "chart-5": "#a8474f",
  "chart-6": "#3d7f9c",
  "skeleton-base": "#dce5eb",
  "skeleton-highlight": "#eef3f6",
};

/** Ember. Mirrors the `ember` theme block in tokens.css. */
export const emberTheme: ColorMap = {
  bg: "#faf6f2",
  surface: "#f1eae4",
  "surface-raised": "#fffdfb",
  "surface-sunken": "#e9e0d8",
  "surface-nav": "#f5efe9",
  "surface-header": "#fbf7f4",
  "surface-card": "#fffdfb",
  text: "#241c18",
  "text-secondary": "#524740",
  "text-muted": "#665951",
  "on-accent": "#ffffff",
  link: "#9a4227",
  "link-hover": "#75311c",
  border: "#e0d5cb",
  "border-strong": "#c5b6a9",
  "border-subtle": "#ece3db",
  "control-border": "#8b8079",
  divider: "#e7ddd4",
  accent: "#a8482b",
  "accent-hover": "#8e3c23",
  "accent-active": "#75311c",
  "accent-text": "#9a4227",
  "accent-surface": "#f7e2d7",
  secondary: "#ece3db",
  "secondary-hover": "#e1d5cb",
  success: "#2c7248",
  "success-surface": "#e1efe4",
  "success-text": "#225939",
  warning: "#8a6100",
  "warning-surface": "#f5eacd",
  "warning-text": "#6d4c00",
  danger: "#b01030",
  "danger-surface": "#fbe0e5",
  "danger-text": "#8f0d27",
  info: "#1f6285",
  "info-surface": "#e0ecf3",
  "info-text": "#194f6b",
  "hover-surface": "#f0e8e1",
  "active-surface": "#e6dcd3",
  "disabled-surface": "#f0e9e3",
  "disabled-text": "#94867d",
  "disabled-border": "#e4dad1",
  "focus-ring": "#a8482b",
  "selection-bg": "#f2d3c2",
  "selection-text": "#3a1d10",
  overlay: "rgba(38, 26, 20, 0.48)",
  "priority-p1": "#b01030",
  "priority-p1-surface": "#fbe0e5",
  "priority-p1-text": "#8f0d27",
  "priority-p2": "#8a6100",
  "priority-p2-surface": "#f5eacd",
  "priority-p2-text": "#6d4c00",
  "priority-p3": "#1f6285",
  "priority-p3-surface": "#e0ecf3",
  "priority-p3-text": "#194f6b",
  "priority-p4": "#726359",
  "priority-p4-surface": "#eee6df",
  "priority-p4-text": "#5c4f47",
  "state-overdue": "#b01030",
  "state-overdue-surface": "#fbe0e5",
  "state-overdue-text": "#8f0d27",
  "state-due-soon": "#8a6100",
  "state-due-soon-surface": "#f5eacd",
  "state-due-soon-text": "#6d4c00",
  "state-completed": "#2c7248",
  "state-completed-surface": "#e1efe4",
  "state-completed-text": "#225939",
  "state-waiting": "#63558f",
  "state-waiting-surface": "#e9e5f1",
  "state-waiting-text": "#4f4373",
  "state-on-hold": "#726359",
  "state-on-hold-surface": "#eee6df",
  "state-on-hold-text": "#5c4f47",
  "progress-track": "#e6dcd3",
  "progress-fill": "#a8482b",
  "progress-complete": "#2c7248",
  "chart-1": "#a8482b",
  "chart-2": "#8a6100",
  "chart-3": "#2c7248",
  "chart-4": "#1f6285",
  "chart-5": "#63558f",
  "chart-6": "#8c4a5e",
  "skeleton-base": "#e9e0d8",
  "skeleton-highlight": "#f5efe9",
};

/** Daly Light entity-identity accents. */
export const dalyLightEntityAccents: EntityAccentMap = {
  area: "#0f6f66",
  goal: "#6d43c4",
  project: "#4348c4",
  task: "#1f7a44",
  note: "#9a5c07",
  meeting: "#b01f45",
  person: "#0d6a80",
  asset: "#5c6470",
  diary: "#96189e",
  review: "#0b5f92",
};

/** Daly Dark entity-identity accents (brighter, so each still clears 3:1 on the dark background). */
export const dalyDarkEntityAccents: EntityAccentMap = {
  area: "#2dd4bf",
  goal: "#a78bfa",
  project: "#818cf8",
  task: "#4ade80",
  note: "#fbbf24",
  meeting: "#fb7185",
  person: "#22d3ee",
  asset: "#94a3b8",
  diary: "#e879f9",
  review: "#38bdf8",
};

/** Eucalypt entity-identity accents. */
export const eucalyptEntityAccents: EntityAccentMap = {
  area: "#0f6a5c",
  goal: "#6a4aad",
  project: "#3f5aa8",
  task: "#2f7040",
  note: "#8a5a10",
  meeting: "#a32f4a",
  person: "#2b6474",
  asset: "#5f6455",
  diary: "#8a2b8f",
  review: "#1f5a80",
};

/** Coastal entity-identity accents. */
export const coastalEntityAccents: EntityAccentMap = {
  area: "#0e6f70",
  goal: "#6247b5",
  project: "#3d54b5",
  task: "#1c7554",
  note: "#8a5c0c",
  meeting: "#a82f52",
  person: "#136580",
  asset: "#5a6873",
  diary: "#8f2496",
  review: "#1f6b9e",
};

/** Ember entity-identity accents. */
export const emberEntityAccents: EntityAccentMap = {
  area: "#0f6a63",
  goal: "#6a45b0",
  project: "#3f51ad",
  task: "#2c7248",
  note: "#8a5a0a",
  meeting: "#a72141",
  person: "#146277",
  asset: "#6a5c53",
  diary: "#8d2489",
  review: "#1f6285",
};

/**
 * Every theme's colour map, keyed by its `data-theme` value. This is the set the
 * token tests iterate, so adding a theme here without adding its CSS block (or the
 * other way round) fails the sync test.
 */
export const THEME_COLOR_MAPS = {
  "daly-light": dalyLightTheme,
  "daly-dark": dalyDarkTheme,
  eucalypt: eucalyptTheme,
  coastal: coastalTheme,
  ember: emberTheme,
} as const satisfies Record<string, ColorMap>;

/** Every theme's entity-accent map, keyed by its `data-theme` value. */
export const THEME_ENTITY_ACCENTS = {
  "daly-light": dalyLightEntityAccents,
  "daly-dark": dalyDarkEntityAccents,
  eucalypt: eucalyptEntityAccents,
  coastal: coastalEntityAccents,
  ember: emberEntityAccents,
} as const satisfies Record<string, EntityAccentMap>;
