/**
 * THEME-01 — the root document's `theme-color`, and nothing else.
 *
 * @generated by scripts/generate-m3-scheme.mjs — do not hand-edit.
 *
 * The page-surface colour of every scheme in both appearances: the ten strings
 * `app/root.tsx` needs to tell the browser what to paint its own chrome. The
 * values are `--md-app-color-surface-page`, taken from the same build as
 * `tokens.css` and `scheme.ts`.
 *
 * ── Why this is not a lookup into `COLOR_SCHEME_PALETTES` ────────────────────
 *
 * Because that table cannot be tree-shaken. Importing it to read one role put
 * 78.4 KB of generated colour data into the ROOT chunk — the one chunk every
 * route loads and the service worker precaches — for a browser chrome bar.
 * `scheme.ts` keeps the full table for the token tests, which run in Node.
 */

/** The page-surface colour of one scheme, in both appearances. */
export interface ThemeColorPair {
  readonly light: string;
  readonly dark: string;
}

/**
 * The scheme keys, restated here so this module types its own record without
 * importing `scheme.ts` — which would defeat the whole point of the split.
 * `app/kernel/preferences/color-scheme.ts` carries the same keys and
 * `test/unit/preferences/color-scheme.test.ts` proves the three agree.
 */
export const THEME_COLOR_SCHEME_KEYS = [
  "violet",
  "electric",
  "pulse",
  "ocean",
  "graphite",
] as const;

/** A generated colour-scheme key, as this module sees it. */
export type ThemeColorSchemeKey = (typeof THEME_COLOR_SCHEME_KEYS)[number];

/** Every scheme's `theme-color`, by scheme key. */
export const COLOR_SCHEME_THEME_COLORS: Record<
  ThemeColorSchemeKey,
  ThemeColorPair
> = {
  violet: { light: "#faf9fd", dark: "#1a1c1e" },
  electric: { light: "#f9f9fe", dark: "#171e27" },
  pulse: { light: "#fcf8fc", dark: "#1a191e" },
  ocean: { light: "#f9f9fc", dark: "#181e23" },
  graphite: { light: "#faf9fb", dark: "#1f2022" },
};
