/**
 * TODAY-02 Tasks kernel — public surface.
 *
 * Modules and the composition boundary import the task contract from here. This
 * barrel intentionally exposes only the storage-independent contract (types,
 * errors, validation and the repository interface). The D1 adapter is NOT
 * re-exported: code wanting persistence constructs it from
 * `app/platform/storage/d1`, keeping the dependency direction pointing at the
 * contract, not the store (mirrors the entity, EntityLink, Activity and spine
 * barrels).
 */

export {
  TASK_STATUSES,
  TASK_PRIORITIES,
  TIME_SECTORS,
  COMMITMENT_STATES,
  TASK_SYSTEM_VIEWS,
  TASK_SORTS,
  TASK_SORT_DIRECTIONS,
  TASK_DUE_STATES,
  TASK_PLANNED_STATES,
  TASK_PARENT_KINDS,
  TASK_RECENCY_WINDOWS,
  TASK_RECENCY_WINDOW_DAYS,
  TASK_COMPLETED_VISIBILITIES,
  WORKSPACE_TASK_GROUP_DIMENSIONS,
  DEFAULT_TASK_DETAILS,
  type TaskSortDirection,
  type TaskDueState,
  type TaskPlannedState,
  type TaskParentKind,
  type TaskRecencyWindow,
  type TaskCompletedVisibility,
  type TaskStatus,
  type TaskPriority,
  type TimeSector,
  type CommitmentState,
  type TaskSystemView,
  type TaskSort,
  type TaskDelegation,
  type TaskDelegationInput,
  type TaskRelationKind,
  type TaskRelation,
  type TaskDetails,
  type TaskView,
  type TaskWaiting,
  type TaskWaitingSubject,
  type GetTaskOptions,
  type UpdateTaskInput,
  type UpdateTaskResult,
  type ReopenTaskResult,
  type ReopenTaskSuccessorOutcome,
  type SetTaskParentInput,
  type SetTaskParentResult,
  type CompleteTaskOptions,
  type SetTaskRecurrenceInput,
  type SetTaskRecurrenceResult,
  type ListTasksInput,
  type ListPlanningTasksInput,
  type ListProjectTasksInput,
  type ProjectTaskListPage,
  type TaskStateFilter,
  type TaskListItem,
  type TaskListPage,
  type SearchTasksInput,
  type TaskSearchHit,
  type SetWaitingInput,
  type SetWaitingResult,
  type ClearWaitingResult,
  type CompleteTaskResult,
  type ListWaitingTasksInput,
  type WaitingTaskListItem,
  type WaitingTaskPage,
  type PlanTaskInput,
  type PlanTaskResult,
  type ClearPlanResult,
  type BulkPlanResult,
  type WorkspaceTaskFilters,
  type ListWorkspaceTasksInput,
  type WorkspaceTaskListPage,
  type WorkspaceTaskGroupDimension,
  type WorkspaceTaskGroup,
  type WorkspaceTaskGrouping,
  type ListWorkspaceTaskGroupsInput,
  type TaskParentCandidate,
  type SearchTaskParentsInput,
  type NewTaskInput,
  type BulkFieldResult,
} from "./task";

export {
  TASK_WAITING_ON,
  WAITING_TARGET_TYPES,
  WAITING_NOTE_MAX_LENGTH,
  RESERVED_TASK_LINK_TYPES,
  TASK_WAITING_STARTED,
  TASK_WAITING_CHANGED,
  TASK_WAITING_CLEARED,
  TASK_PLANNED,
  TASK_RESCHEDULED,
  TASK_PLAN_CLEARED,
  TASK_RECURRENCE_OCCURRENCE_CREATED,
  TASK_RECURRENCE_OCCURRENCE_WITHDRAWN,
  DELEGATE_TO_MAX_LENGTH,
  DELEGATION_NOTE_MAX_LENGTH,
  MAX_PLAN_BATCH_SIZE,
  isWaitingTargetType,
  isReservedTaskLinkType,
  type WaitingTargetType,
} from "./task-identifiers";

export type { TaskRepository } from "./task-repository";

export {
  TASK_RECURRENCE_DATE_KINDS,
  TASK_RECURRENCE_FREQUENCIES,
  TASK_RECURRENCE_SERIES_ID_MAX_LENGTH,
  addCalendarDays,
  calendarDaysBetween,
  nextTaskOccurrenceDate,
  recurrenceAnchorField,
  resolveTaskRecurrenceRule,
  validateTaskRecurrenceRule,
  weekdayOfDate,
  type TaskRecurrenceDateKind,
  type TaskRecurrenceFrequency,
  type TaskRecurrenceInput,
  type TaskRecurrenceRule,
  type TaskRecurrenceSeries,
} from "./task-recurrence";

export {
  PROJECT_TASK_CURSOR_VERSION,
  encodeProjectTaskCursor,
  decodeProjectTaskCursor,
  decodeProjectTaskCursorForScope,
  projectTaskCursorScopeMatches,
} from "./task-project-cursor";
export type {
  ProjectTaskCursorPosition,
  ProjectTaskCursorScope,
  DecodedProjectTaskCursor,
} from "./task-project-cursor";

export {
  WORKSPACE_TASK_CURSOR_VERSION,
  workspaceTaskFiltersSignature,
  encodeWorkspaceTaskCursor,
  decodeWorkspaceTaskCursor,
  decodeWorkspaceTaskCursorForScope,
  workspaceTaskCursorScopeMatches,
} from "./task-workspace-cursor";
export type {
  WorkspaceTaskCursorPosition,
  WorkspaceTaskCursorScope,
  DecodedWorkspaceTaskCursor,
} from "./task-workspace-cursor";

export {
  TaskError,
  TaskValidationError,
  TaskNotFoundError,
  TaskStorageError,
  CorruptTaskRecordError,
  TaskProjectArchivedError,
  type TaskErrorCode,
  type TaskValidationField,
} from "./task-errors";

export {
  DEFAULT_TASK_PAGE_SIZE,
  MAX_TASK_PAGE_SIZE,
  validateTaskId,
  validateTaskTitle,
  isTaskStatus,
  validateTaskStatus,
  validateTaskPriority,
  validateTimeSector,
  validateCommitmentState,
  validateDelegateTo,
  validateDelegationNote,
  validateDelegationInput,
  validateTaskSystemView,
  validateTaskSort,
  validateTaskSortDirection,
  validateTaskDueState,
  validateTaskPlannedState,
  validateTaskParentKind,
  validateTaskRecencyWindow,
  validateTaskCompletedVisibility,
  validateTaskGroupDimension,
  shiftCalendarDate,
  weekWindowEnd,
  recencyWindowStart,
  validateTaskDate,
  validateTaskDescription,
  validateTaskLimit,
  validateWaitingNote,
  validateWaitingTargetId,
  validateSetWaitingInput,
  validatePlanDate,
  validateTaskIdList,
} from "./task-validation";
