-- Migration number: 0001 	 2026-07-17
--
-- FND-02 Data kernel: the central `entities` table.
--
-- This table holds the identity and lifecycle that EVERY DalyHub record shares
-- (see ADR-009 and docs/architecture/ARCHITECTURE_OVERVIEW.md). It deliberately
-- contains only the shared fields — id, workspace, type, title, timestamps and
-- soft-delete. Domain-specific fields (status, dates, progress, body, …) belong
-- to future domain tables, never to this substrate.
--
-- Conventions:
--   * Timestamps are stored as ISO-8601 UTC TEXT (e.g. 2026-07-17T12:34:56.789Z)
--     generated by the application, so database and application time never
--     disagree. Fixed-width ISO strings also sort chronologically, which keeps
--     cursor pagination stable.
--   * `type` is a free-form identifier validated by the kernel, NOT a database
--     enum, so future modules can register entity types without a migration.
--   * STRICT enforces column typing so a schema mistake fails loudly.

CREATE TABLE entities (
  id           TEXT NOT NULL PRIMARY KEY,
  workspace_id TEXT NOT NULL,
  type         TEXT NOT NULL,
  title        TEXT NOT NULL,
  created_at   TEXT NOT NULL,
  updated_at   TEXT NOT NULL,
  deleted_at   TEXT,
  CONSTRAINT entities_id_not_empty CHECK (length(id) > 0),
  CONSTRAINT entities_workspace_id_not_empty CHECK (length(workspace_id) > 0),
  CONSTRAINT entities_type_not_empty CHECK (length(type) > 0),
  CONSTRAINT entities_title_not_empty CHECK (length(trim(title)) > 0)
) STRICT;

-- Access path: list all entities in a workspace, newest-stable ordering.
-- (workspace_id, created_at, id) matches "WHERE workspace_id = ? ORDER BY
-- created_at, id" and the (created_at, id) cursor tuple.
CREATE INDEX entities_workspace_created_idx
  ON entities (workspace_id, created_at, id);

-- Access path: list entities of one type in a workspace.
CREATE INDEX entities_workspace_type_created_idx
  ON entities (workspace_id, type, created_at, id);

-- Access path: the DEFAULT list/read path excludes soft-deleted rows. Partial
-- indexes over the not-deleted subset keep those hot queries small and fast.
CREATE INDEX entities_active_workspace_created_idx
  ON entities (workspace_id, created_at, id)
  WHERE deleted_at IS NULL;

CREATE INDEX entities_active_workspace_type_created_idx
  ON entities (workspace_id, type, created_at, id)
  WHERE deleted_at IS NULL;
