-- Migration number: 0032 	 2026-08-06
--
-- Selectable Area and Project icons.
--
-- An Area or a Project may carry a chosen icon. Both are stored the way every
-- other additive Area/Project detail is stored (the `project_details` /
-- `area_details` precedent, ADR-037 / ADR-039): a nullable column on the
-- module-owned detail table keyed by `(workspace_id, entity_id)`, written only
-- through the trusted settings repository. This is not a second identity model -
-- it holds one nullable key and nothing the spine already owns.
--
-- WHAT IS STORED. A controlled semantic KEY and nothing else: `folder`, `travel`,
-- `property`. Never SVG, never HTML, never an icon-font codepoint, never a React
-- component name, never a URL, never arbitrary text, never an emoji. The key is
-- resolved to a component in the UI, so the drawing can change without the data
-- changing, and a stored key can never carry markup into a page.
--
-- There is deliberately NO CHECK naming the permitted keys. The authoritative
-- list lives in `app/kernel/entities/entity-icon-keys.ts` and is enforced at the
-- validation boundary, which every write already passes through. A CHECK naming
-- thirty values is a schema that needs a migration every time the catalogue
-- gains an icon - exactly the mistake `owner_app_preferences.theme` made, which
-- migration 0031 had to rebuild a whole table to undo. Leaving the column
-- unconstrained also keeps a future `DROP COLUMN` cheap, since SQLite cannot
-- drop a column that participates in a CHECK.
--
-- The cost of that choice is bounded by design: an unrecognised key renders the
-- entity's DEFAULT icon rather than throwing, so a key left behind by a removed
-- catalogue entry degrades invisibly instead of breaking the page.
--
-- NO BACKFILL. Every existing Area and Project stays valid with `icon_key` NULL,
-- which means "use the entity's default icon" - the same thing a missing detail
-- row already means everywhere else. Nothing is rewritten and nothing is lost.
--
-- Purely ADDITIVE: two `ALTER TABLE ... ADD COLUMN` statements. No table is
-- rebuilt, no existing column, constraint, index or row is touched, and neither
-- column participates in a CHECK that would prevent a later `DROP COLUMN`.

ALTER TABLE area_details ADD COLUMN icon_key TEXT;

ALTER TABLE project_details ADD COLUMN icon_key TEXT;
