/**
 * AI-01 kernel — the provider-independent AI contracts.
 *
 * Everything exported here is pure and dependency-free: no React, no D1, no
 * Cloudflare bindings, no provider SDK, no secret. Modules import from here;
 * provider and transport detail lives in `app/platform/ai/`.
 */

export {
  AI_ERROR_CODES,
  AiError,
  aiErrorMessage,
  aiErrorStatus,
  isAiError,
  isAiErrorCode,
  isPolicyError,
  isTransientError,
  toAiError,
  type AiErrorCode,
} from "./ai-errors";

export {
  AI_MODEL_REGISTRY,
  AI_MODEL_TIERS,
  AI_PROVIDERS,
  MODEL_AVAILABILITY,
  PRICING_VERIFIED_AT,
  PRICING_VERSION,
  STRUCTURED_OUTPUT_METHODS,
  costUnavailable,
  estimateCostUsd,
  estimateTokens,
  findAiModel,
  isAiModelTier,
  isAiProvider,
  isBudgetable,
  isSameOrCheaperTier,
  modelsForProvider,
  resolveModel,
  type AiModelEntry,
  type AiModelTier,
  type AiProvider,
  type ModelAvailability,
  type StructuredOutputMethod,
} from "./ai-models";

export {
  AI_FEATURE_IDS,
  aiFeaturePolicy,
  allAiFeaturePolicies,
  isAiFeatureId,
  parseAiFeatureId,
  resolveRequestedTier,
  type AiFeatureId,
  type AiFeaturePolicy,
} from "./ai-features";

export {
  EMPTY_EVIDENCE_SET,
  EVIDENCE_KINDS,
  PRIVACY_CATEGORIES,
  SENSITIVE_CATEGORIES,
  defaultCategoryForKind,
  evidenceDisclosure,
  evidenceIdForIndex,
  evidenceKindLabel,
  isPrivacyCategory,
  isSensitiveCategory,
  privacyCategoryLabel,
  renderEvidenceBlock,
  sanitiseForPrompt,
  selectEvidence,
  truncateExcerpt,
  type EvidenceCandidate,
  type EvidenceItem,
  type EvidenceKind,
  type EvidenceLimits,
  type EvidenceSet,
  type PrivacyCategory,
} from "./ai-evidence";

export {
  AI_LOGGING_MODES,
  AI_RESULT_RETENTION_CHOICES,
  AiPreferencesValidationError,
  DEFAULT_AI_PREFERENCES,
  DEFAULT_DAILY_BUDGET_USD,
  DEFAULT_MONTHLY_BUDGET_USD,
  DEFAULT_PREMIUM_BUDGET_USD,
  MAX_CONCURRENT_AI_REQUESTS,
  MAX_DAILY_BUDGET_USD,
  MAX_MONTHLY_BUDGET_USD,
  MAX_PREMIUM_BUDGET_USD,
  aliasForTier,
  featureAllowed,
  normaliseAiPreferences,
  parseAiBoolean,
  parseAiLoggingMode,
  parseAiModelTier,
  parseAiProvider,
  parseAiResultRetention,
  parseBudgetUsd,
  permittedCategories,
  type AiLoggingMode,
  type AiPreferencePatch,
  type AiPreferenceRecord,
  type AiPreferences,
  type AiPreferencesChangeResult,
  type AiPreferencesRepository,
  type AiResultRetention,
} from "./ai-preferences";

export {
  EMPTY_BUDGET_TOTALS,
  budgetPeriodKeys,
  budgetRemaining,
  budgetSnapshot,
  checkBudget,
  formatUsd,
  reconcile,
  releaseUnused,
  type BudgetCheckInput,
  type BudgetDecision,
  type BudgetPeriodKeys,
  type BudgetRemaining,
  type BudgetSnapshot,
  type BudgetUsageTotals,
  type Reconciliation,
} from "./ai-budget";

export {
  AI_ATTEMPT_KINDS,
  AI_PROPOSAL_OUTCOMES,
  AI_REQUEST_STATES,
  MAX_RECORDED_SOURCE_IDS,
  canTransition,
  isAiProposalOutcome,
  isAiRequestState,
  isTerminalRequestState,
  transition,
  type AiAttemptKind,
  type AiFeatureUsageTotal,
  type AiProposalOutcome,
  type AiRequestState,
  type AiUsageRecord,
  type AiUsageRepository,
  type CompleteAiRequestInput,
  type StartAiRequestInput,
} from "./ai-usage";

export {
  computeFingerprint,
  fingerprintSource,
  isReusable,
  reuseWindowMs,
  sha256Hex,
  type FingerprintInput,
} from "./ai-fingerprint";

export {
  ACTION_EXTRACTION_SCHEMA,
  CLAIM_CLASSIFICATIONS,
  CONFIDENCE_LEVELS,
  COUNTS,
  EMPTY_VALIDATION_CONTEXT,
  LIMITS,
  MEETING_EXTRACTION_SCHEMA,
  NOTE_PURPOSES,
  WEEKLY_REVIEW_SCHEMA,
  WORKSPACE_ANSWER_SCHEMA,
  isExtractionResult,
  isProposedNotePurpose,
  parseIsoCalendarDate,
  proposedNotesOf,
  schemaForFeature,
  validateActionExtraction,
  validateFeatureResult,
  validateMeetingExtraction,
  validateWeeklyReviewAssistant,
  validateWorkspaceAnswer,
  type ActionExtractionResult,
  type AiResult,
  type AnswerStatement,
  type AttentionItem,
  type CitedStatement,
  type ClaimClassification,
  type ConfidenceLevel,
  type ExtractedDecision,
  type ExtractionResult,
  type JsonSchema,
  type MeetingExtractionResult,
  type ObservedPattern,
  type ProposedNote,
  type ProposedNotePurpose,
  type ProposedTask,
  type SuggestedLink,
  type UnresolvedQuestion,
  type ValidationContext,
  type WeeklyReviewAssistantResult,
  type WorkspaceAnswerResult,
} from "./ai-schemas";

export {
  allPrompts,
  buildUserMessage,
  promptForFeature,
  type PromptDefinition,
} from "./ai-prompts";

export {
  executeWithPolicy,
  totalUsage,
  type AiProviderAdapter,
  type AttemptKind,
  type AttemptRecord,
  type ExecutionPlan,
  type ExecutionResult,
  type ProviderUsage,
  type StructuredRequest,
  type StructuredResponse,
} from "./ai-client";
