/**
 * Test helper: read and parse `app/styles/tokens.css`.
 *
 * The M3-01 token tests treat the stylesheet as the authoritative source of
 * values and assert structural guarantees against it (the generated blocks match
 * the generator, every role and structural token is defined, every legacy name
 * still resolves through the alias layer, and no consumer references a token the
 * stylesheet never defines). Parsing is deliberately simple: the token blocks
 * contain no nested rules, so balanced-brace extraction plus a declaration regex
 * suffices.
 */

import { readdirSync, readFileSync, statSync } from "node:fs";
import path from "node:path";

// Under Vitest `import.meta.url` may not be a `file:` URL, so resolve from the
// repo root (the working directory) instead.
const APP_DIR = path.join(process.cwd(), "app");

/** Read a file under `app/` as text. */
export function readAppFile(relativePath: string): string {
  return readFileSync(path.join(APP_DIR, relativePath), "utf8");
}

/** The full tokens stylesheet text. */
export const tokensCss = readAppFile("styles/tokens.css");

/** The marker that opens the generated colour section. */
export const GENERATED_BEGIN =
  "/* @generated by scripts/generate-m3-scheme.mjs — do not hand-edit */";

/** The marker that closes it. */
export const GENERATED_END =
  "/* @end generated by scripts/generate-m3-scheme.mjs */";

/** Extract the `{ … }` body that follows the first match of `header` in `css`,
 * using balanced-brace matching. Returns the inner text (without the braces). */
export function blockBody(css: string, header: RegExp): string {
  const match = header.exec(css);
  if (match === null) {
    throw new Error(`selector not found: ${header}`);
  }
  const open = css.indexOf("{", match.index + match[0].length - 1);
  if (open === -1) {
    throw new Error(`opening brace not found for: ${header}`);
  }
  let depth = 0;
  for (let i = open; i < css.length; i += 1) {
    if (css[i] === "{") {
      depth += 1;
    } else if (css[i] === "}") {
      depth -= 1;
      if (depth === 0) {
        return css.slice(open + 1, i);
      }
    }
  }
  throw new Error(`unbalanced braces for: ${header}`);
}

/** Parse `--name: value;` declarations from a block body into a Map. */
export function parseDeclarations(blockText: string): Map<string, string> {
  const declarations = new Map<string, string>();
  const re = /--([\w-]+)\s*:\s*([^;]+);/g;
  let match: RegExpExecArray | null;
  while ((match = re.exec(blockText)) !== null) {
    declarations.set(match[1].trim(), match[2].trim());
  }
  return declarations;
}

/** The generated section, between (and excluding) the two markers. */
export function generatedSection(): string {
  const begin = tokensCss.indexOf(GENERATED_BEGIN);
  const end = tokensCss.indexOf(GENERATED_END);
  if (begin === -1 || end === -1) {
    throw new Error("tokens.css is missing the generated markers");
  }
  return tokensCss.slice(begin + GENERATED_BEGIN.length, end);
}

/** The LIGHT scheme block — the `:root` inside the generated section. */
export function lightSchemeTokens(): Map<string, string> {
  return parseDeclarations(blockBody(generatedSection(), /:root\s*\{/));
}

/**
 * The DARK scheme block — the rule inside the generated `prefers-color-scheme`
 * media query.
 *
 * APPEARANCE-01 narrowed that rule's selector from `:root` to
 * `:root:not([data-appearance="light"])`, so a device set to dark no longer
 * overrides an owner who explicitly chose Light. The declarations are unchanged,
 * and `explicitDarkSchemeTokens()` asserts that the explicit-dark block outside
 * the media query carries exactly the same ones.
 */
export function darkSchemeTokens(): Map<string, string> {
  const media = blockBody(
    generatedSection(),
    /@media\s*\(prefers-color-scheme:\s*dark\)\s*\{/,
  );
  return parseDeclarations(
    blockBody(media, /:root:not\(\[data-appearance="light"\]\)\s*\{/),
  );
}

/**
 * The EXPLICIT dark block — `:root[data-appearance="dark"]`, which paints dark on
 * a device set to light. It must carry the same declarations as the media-query
 * block, or an explicit Dark would be a different (partial) dark appearance.
 */
export function explicitDarkSchemeTokens(): Map<string, string> {
  return parseDeclarations(
    blockBody(generatedSection(), /:root\[data-appearance="dark"\]\s*\{/),
  );
}

/**
 * The EXPLICIT light block — `:root[data-appearance="light"]`. It carries no
 * colour declarations (the base `:root` already paints light); its whole job is to
 * pin `color-scheme` so native controls do not follow a dark device.
 */
export function explicitLightBlock(): string {
  return blockBody(generatedSection(), /:root\[data-appearance="light"\]\s*\{/);
}

/** Every custom property defined anywhere in the stylesheet, name → value.
 * Later definitions win, which is what the cascade does for `:root` blocks. */
export function allTokens(): Map<string, string> {
  return parseDeclarations(tokensCss);
}

/** Every custom-property NAME defined anywhere in tokens.css. */
export function allDefinedTokenNames(): Set<string> {
  return new Set(allTokens().keys());
}

/**
 * Resolve a token to the chain of token names it depends on, following
 * `var(--…)` references transitively. Throws if a reference is undefined, which
 * is exactly the failure an alias typo produces in the browser (the property
 * resolves to nothing and the rule is dropped).
 */
export function resolveTokenChain(
  name: string,
  tokens: Map<string, string> = allTokens(),
  seen: Set<string> = new Set(),
): readonly string[] {
  if (seen.has(name)) {
    throw new Error(`circular token reference at --${name}`);
  }
  seen.add(name);
  const value = tokens.get(name);
  if (value === undefined) {
    throw new Error(`undefined token --${name}`);
  }
  const chain = [name];
  for (const match of value.matchAll(/var\(\s*--([\w-]+)/g)) {
    chain.push(...resolveTokenChain(match[1], tokens, seen));
  }
  return chain;
}

/** Every source file under `app/` that can reference a token. */
export function appSourceFiles(): readonly string[] {
  const out: string[] = [];
  const walk = (dir: string) => {
    for (const entry of readdirSync(dir)) {
      const full = path.join(dir, entry);
      if (statSync(full).isDirectory()) {
        walk(full);
      } else if (/\.(css|tsx?)$/.test(entry)) {
        out.push(full);
      }
    }
  };
  walk(APP_DIR);
  return out;
}

/** A repo-relative path for a file returned by `appSourceFiles`. */
export function repoRelative(file: string): string {
  return path.relative(process.cwd(), file);
}

/** An `app/`-relative path for a file returned by `appSourceFiles`. */
export function appRelative(file: string): string {
  return path.relative(APP_DIR, file);
}
