/**
 * M3-01 — token system structural guarantees.
 *
 * These tests treat `app/styles/tokens.css` as the authoritative source and
 * enforce the acceptance criteria for the Material Design 3 token layer:
 *
 *   - the generated colour blocks are byte-identical to what the generator
 *     produces, so a hand-edited hex fails here as well as in `scheme:check`;
 *   - every system role, custom colour and application surface is defined in
 *     BOTH schemes;
 *   - every structural (non-colour) token the registry names exists;
 *   - every LEGACY `--dh-*` name still resolves through the alias layer, so the
 *     mid-migration application is never silently unstyled;
 *   - no consumer references a token the stylesheet does not define;
 *   - the retired theme mechanism is genuinely gone.
 */

import { execFileSync } from "node:child_process";

import { describe, expect, it } from "vitest";

import {
  BREAKPOINTS,
  REQUIRED_TOKEN_NAMES,
  SCHEME_ROLE_NAMES,
  DARK_SCHEME,
  LIGHT_SCHEME,
} from "~/shared/tokens";

import { LEGACY_TOKEN_NAMES } from "./legacy-token-names";
import {
  allDefinedTokenNames,
  allTokens,
  appRelative,
  appSourceFiles,
  darkSchemeTokens,
  lightSchemeTokens,
  readAppFile,
  repoRelative,
  resolveTokenChain,
  tokensCss,
} from "./token-css";

/** The CSS custom-property name for a scheme role. */
function tokenNameFor(role: string): string {
  return role.startsWith("app-")
    ? `md-app-color-${role.slice("app-".length)}`
    : `md-sys-color-${role}`;
}

describe("M3-01 the scheme is generated, not authored", () => {
  it("matches the generator byte for byte", () => {
    // The same check `pnpm run verify` runs, asserted here too so a drifted hex
    // fails the unit suite rather than only the pipeline step after it.
    const result = execFileSync(
      process.execPath,
      ["scripts/generate-m3-scheme.mjs", "--check"],
      {
        cwd: process.cwd(),
        encoding: "utf8",
        stdio: ["ignore", "pipe", "pipe"],
      },
    );
    expect(result).toContain("match the generator");
  });

  it("wraps the colour blocks in the generated markers", () => {
    expect(tokensCss).toContain(
      "/* @generated by scripts/generate-m3-scheme.mjs — do not hand-edit */",
    );
    expect(tokensCss).toContain(
      "/* @end generated by scripts/generate-m3-scheme.mjs */",
    );
  });

  it("opts the document into both colour schemes", () => {
    expect(lightSchemeTokens()).toBeDefined();
    expect(tokensCss).toMatch(/color-scheme:\s*light dark;/);
  });
});

describe("M3-01 colour role coverage", () => {
  const light = lightSchemeTokens();
  const dark = darkSchemeTokens();

  it("defines every role in the light scheme", () => {
    for (const role of SCHEME_ROLE_NAMES) {
      const token = tokenNameFor(role);
      expect(
        light.get(token),
        `light scheme is missing --${token}`,
      ).toBeTruthy();
    }
  });

  it("defines every role in the dark scheme", () => {
    for (const role of SCHEME_ROLE_NAMES) {
      const token = tokenNameFor(role);
      expect(dark.get(token), `dark scheme is missing --${token}`).toBeTruthy();
    }
  });

  it("mirrors the CSS values in the TS scheme data", () => {
    for (const role of SCHEME_ROLE_NAMES) {
      const token = tokenNameFor(role);
      if (role.startsWith("app-")) {
        // The application surfaces are aliases in CSS and resolved hexes in TS;
        // the TS value must equal the system rung the CSS alias points at.
        const reference = /var\(\s*--md-sys-color-([\w-]+)\)/.exec(
          light.get(token)!,
        )![1];
        expect(LIGHT_SCHEME[role]).toBe(
          LIGHT_SCHEME[reference as (typeof SCHEME_ROLE_NAMES)[number]],
        );
        const darkReference = /var\(\s*--md-sys-color-([\w-]+)\)/.exec(
          dark.get(token)!,
        )![1];
        expect(DARK_SCHEME[role]).toBe(
          DARK_SCHEME[darkReference as (typeof SCHEME_ROLE_NAMES)[number]],
        );
        continue;
      }
      expect(light.get(token), `light --${token}`).toBe(LIGHT_SCHEME[role]);
      expect(dark.get(token), `dark --${token}`).toBe(DARK_SCHEME[role]);
    }
  });

  it("actually changes colour between the two schemes", () => {
    expect(DARK_SCHEME["app-surface-page"]).not.toBe(
      LIGHT_SCHEME["app-surface-page"],
    );
    expect(DARK_SCHEME["on-surface"]).not.toBe(LIGHT_SCHEME["on-surface"]);
  });

  it("keeps a card lighter than its page in BOTH schemes", () => {
    // The whole reason the four `--md-app-color-*` extensions exist: one system
    // alias cannot express "the card lifts off the page" in light AND dark,
    // because light lifts toward white and dark lifts away from black.
    const luminance = (hex: string) => {
      const channels = [1, 3, 5].map((i) => {
        const v = parseInt(hex.slice(i, i + 2), 16) / 255;
        return v <= 0.03928 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4;
      });
      return 0.2126 * channels[0] + 0.7152 * channels[1] + 0.0722 * channels[2];
    };
    for (const [name, scheme] of [
      ["light", LIGHT_SCHEME],
      ["dark", DARK_SCHEME],
    ] as const) {
      expect(
        luminance(scheme["app-surface-card"]),
        `${name}: the card must be lighter than the page`,
      ).toBeGreaterThan(luminance(scheme["app-surface-page"]));
    }
  });
});

describe("M3-01 required tokens", () => {
  const defined = allDefinedTokenNames();

  it("defines every required token (colour and structural)", () => {
    for (const name of REQUIRED_TOKEN_NAMES) {
      expect(defined.has(name), `missing token --${name}`).toBe(true);
    }
  });

  it("keeps breakpoint tokens in sync with the TS scale", () => {
    const tokens = allTokens();
    const remToPx = (rem: string) => Math.round(parseFloat(rem) * 16);
    expect(remToPx(tokens.get("dh-breakpoint-sm")!)).toBe(BREAKPOINTS.sm);
    expect(remToPx(tokens.get("dh-breakpoint-md")!)).toBe(BREAKPOINTS.md);
    expect(remToPx(tokens.get("dh-breakpoint-lg")!)).toBe(BREAKPOINTS.lg);
    expect(remToPx(tokens.get("dh-breakpoint-xl")!)).toBe(BREAKPOINTS.xl);
    expect(remToPx(tokens.get("dh-breakpoint-2xl")!)).toBe(BREAKPOINTS["2xl"]);
  });
});

describe("M3-01 the alias layer covers every legacy token", () => {
  const tokens = allTokens();

  it("still resolves every name the old system defined", () => {
    const missing = LEGACY_TOKEN_NAMES.filter((name) => !tokens.has(name));
    expect(
      missing,
      `these legacy tokens have no definition, so every rule that reads one is silently dropped: ${missing.join(", ")}`,
    ).toEqual([]);
  });

  it("resolves every legacy token to a real value, never to nothing", () => {
    const broken: string[] = [];
    for (const name of LEGACY_TOKEN_NAMES) {
      if (!tokens.has(name)) continue;
      try {
        resolveTokenChain(name, tokens);
      } catch (error) {
        broken.push(`--${name}: ${(error as Error).message}`);
      }
    }
    expect(broken).toEqual([]);
  });

  it("never grows: the alias layer is a one-way door", () => {
    // A new `--dh-*` name would mean a component was written against the retired
    // vocabulary. The count only ever falls.
    const dhTokens = [...tokens.keys()].filter((name) =>
      name.startsWith("dh-"),
    );
    expect(dhTokens.length).toBeLessThanOrEqual(LEGACY_TOKEN_NAMES.length);
    const added = dhTokens.filter((name) => !LEGACY_TOKEN_NAMES.includes(name));
    expect(added, `new legacy-prefixed tokens: ${added.join(", ")}`).toEqual(
      [],
    );
  });
});

describe("M3-01 no consumer references an undefined token", () => {
  const defined = allDefinedTokenNames();

  it("every var(--md-*) and var(--dh-*) used in app/ is defined", () => {
    const referenced = new Map<string, string>(); // token -> first file
    const re = /var\(\s*--((?:md|dh|app)-[\w-]+)/g;
    for (const file of appSourceFiles()) {
      // The token registry itself CONSTRUCTS `var(--md-sys-color-<role>)`
      // dynamically; it is the source of truth, not a consumer.
      if (appRelative(file).startsWith("shared/tokens")) continue;
      const text = readAppFile(appRelative(file));
      let match: RegExpExecArray | null;
      while ((match = re.exec(text)) !== null) {
        if (!referenced.has(match[1])) {
          referenced.set(match[1], repoRelative(file));
        }
      }
    }

    expect(referenced.size).toBeGreaterThan(0);
    for (const [token, file] of referenced) {
      // The theme PREVIEW is the one documented place that sets its own custom
      // properties inline (it must paint a scheme it is not in), so
      // `--dh-preview-*` is defined by `ThemePreview`, not by tokens.css.
      if (token.startsWith("dh-preview-")) continue;
      expect(
        defined.has(token),
        `undefined token --${token} used in ${file}`,
      ).toBe(true);
    }
  });
});

describe("M3-01 the seven-theme mechanism is gone", () => {
  it("declares no `data-theme` palette in the stylesheet", () => {
    expect(tokensCss).not.toContain('[data-theme="');
  });

  it("selects dark by the OS preference alone", () => {
    expect(tokensCss).toContain("@media (prefers-color-scheme: dark)");
  });

  it("honours prefers-reduced-motion in the base styles", () => {
    const baseCss = readAppFile("styles/base.css");
    expect(baseCss).toContain("@media (prefers-reduced-motion: reduce)");
    expect(baseCss).toMatch(
      /transition-duration:\s*var\(--md-sys-motion-duration-none\)/,
    );
  });
});
