/**
 * M3-01 — token system structural guarantees.
 *
 * These tests treat `app/styles/tokens.css` as the authoritative source and
 * enforce the acceptance criteria for the Material Design 3 token layer:
 *
 *   - the generated colour blocks are byte-identical to what the generator
 *     produces, so a hand-edited hex fails here as well as in `scheme:check`;
 *   - every system role, custom colour and application surface is defined in
 *     BOTH schemes;
 *   - every structural (non-colour) token the registry names exists;
 *   - no `--dh-*` name survives anywhere: the alias layer is retired and the
 *     structural survivors are renamed `--app-*`;
 *   - no consumer references a token the stylesheet does not define;
 *   - the retired theme mechanism is genuinely gone.
 */

import { execFileSync } from "node:child_process";

import { Hct, argbFromHex } from "@material/material-color-utilities";
import { describe, expect, it } from "vitest";

import {
  BREAKPOINTS,
  COLOR_SCHEME_PALETTES,
  GENERATED_COLOR_SCHEMES,
  REQUIRED_TOKEN_NAMES,
  SCHEME_ROLE_NAMES,
  DARK_SCHEME,
  LIGHT_SCHEME,
} from "~/shared/tokens";

import { LEGACY_STRUCTURAL_TOKEN_NAMES } from "./legacy-token-names";
import {
  allDefinedTokenNames,
  allTokens,
  appRelative,
  appSourceFiles,
  darkSchemeTokens,
  lightSchemeTokens,
  readAppFile,
  repoRelative,
  schemeDarkTokens,
  schemeLightTokens,
  tokensCss,
} from "./token-css";

/** Both appearances of the DEFAULT scheme, for assertions that name it. */
const BOTH_SCHEMES = [
  ["light", LIGHT_SCHEME],
  ["dark", DARK_SCHEME],
] as const;

/**
 * THEME-01 — every scheme in every appearance, labelled.
 *
 * Each structural guarantee below is a statement about what the APPLICATION looks
 * like, not about one palette, so it has to hold ten times over rather than
 * twice. A ladder that only holds for the default scheme is a ladder that breaks
 * the first time an owner picks another one.
 */
const EVERY_SCHEME = GENERATED_COLOR_SCHEMES.flatMap((scheme) =>
  (["light", "dark"] as const).map(
    (appearance) =>
      [
        `${scheme}/${appearance}`,
        COLOR_SCHEME_PALETTES[scheme][appearance],
      ] as const,
  ),
);

/** The three sRGB channels of a `#rrggbb` string. */
function rgb(hex: string): [number, number, number] {
  return [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16)) as [
    number,
    number,
    number,
  ];
}

/** WCAG relative luminance. */
function luminance(hex: string): number {
  const channels = rgb(hex).map((v) => {
    const c = v / 255;
    return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4;
  });
  return 0.2126 * channels[0] + 0.7152 * channels[1] + 0.0722 * channels[2];
}

/**
 * HCT chroma — "how much colour is in this", independent of how light it is.
 *
 * Read from `@material/material-color-utilities`, the same library the generator
 * derives the scheme with, so "low chroma" here means exactly what it means
 * there rather than approximately. It is a dev dependency and this is a dev
 * test; nothing in the app or the Worker imports it.
 */
function chroma(hex: string): number {
  return Hct.fromInt(argbFromHex(hex)).chroma;
}

/** HCT tone — L*, and therefore perceptually uniform at both ends of the ramp. */
function tone(hex: string): number {
  return Hct.fromInt(argbFromHex(hex)).tone;
}

/** The CSS custom-property name for a scheme role. */
function tokenNameFor(role: string): string {
  return role.startsWith("app-")
    ? `md-app-color-${role.slice("app-".length)}`
    : `md-sys-color-${role}`;
}

describe("M3-01 the scheme is generated, not authored", () => {
  it("matches the generator byte for byte", () => {
    // The same check `pnpm run verify` runs, asserted here too so a drifted hex
    // fails the unit suite rather than only the pipeline step after it.
    const result = execFileSync(
      process.execPath,
      ["scripts/generate-m3-scheme.mjs", "--check"],
      {
        cwd: process.cwd(),
        encoding: "utf8",
        stdio: ["ignore", "pipe", "pipe"],
      },
    );
    expect(result).toContain("match the generator");
  });

  it("wraps the colour blocks in the generated markers", () => {
    expect(tokensCss).toContain(
      "/* @generated by scripts/generate-m3-scheme.mjs — do not hand-edit */",
    );
    expect(tokensCss).toContain(
      "/* @end generated by scripts/generate-m3-scheme.mjs */",
    );
  });

  it("opts the document into both colour schemes", () => {
    expect(lightSchemeTokens()).toBeDefined();
    expect(tokensCss).toMatch(/color-scheme:\s*light dark;/);
  });
});

describe("M3-01 colour role coverage", () => {
  const light = lightSchemeTokens();
  const dark = darkSchemeTokens();

  it("defines every role in the light scheme", () => {
    for (const role of SCHEME_ROLE_NAMES) {
      const token = tokenNameFor(role);
      expect(
        light.get(token),
        `light scheme is missing --${token}`,
      ).toBeTruthy();
    }
  });

  it("defines every role in the dark scheme", () => {
    for (const role of SCHEME_ROLE_NAMES) {
      const token = tokenNameFor(role);
      expect(dark.get(token), `dark scheme is missing --${token}`).toBeTruthy();
    }
  });

  it("defines every role in EVERY colour scheme, in both appearances", () => {
    // THEME-01 §41 — a scheme that is missing a role does not fail loudly: the
    // browser falls through to whatever the previous block left behind, and the
    // product looks almost right. So the check is exhaustive and cheap rather
    // than sampled.
    for (const scheme of GENERATED_COLOR_SCHEMES) {
      for (const role of SCHEME_ROLE_NAMES) {
        for (const [appearance, value] of [
          ["light", COLOR_SCHEME_PALETTES[scheme].light[role]],
          ["dark", COLOR_SCHEME_PALETTES[scheme].dark[role]],
        ] as const) {
          expect(value, `${scheme}/${appearance} is missing ${role}`).toMatch(
            /^#[0-9a-f]{6}$/,
          );
        }
      }
    }
  });

  it("mirrors the CSS values in the TS scheme data, for every scheme", () => {
    // Every role — system, custom and application alike — is a literal hex in
    // both artefacts. The application surfaces used to be `var()` aliases onto
    // the system container ramp and needed dereferencing here; they now come
    // out of their own generated app-neutral palette, so there is nothing left
    // to special-case.
    for (const scheme of GENERATED_COLOR_SCHEMES) {
      const cssLight = schemeLightTokens(scheme);
      const cssDark = schemeDarkTokens(scheme);
      for (const role of SCHEME_ROLE_NAMES) {
        const token = tokenNameFor(role);
        expect(cssLight.get(token), `${scheme} light --${token}`).toBe(
          COLOR_SCHEME_PALETTES[scheme].light[role],
        );
        expect(cssDark.get(token), `${scheme} dark --${token}`).toBe(
          COLOR_SCHEME_PALETTES[scheme].dark[role],
        );
      }
    }
    // The default scheme's aliases still point at the default scheme.
    expect(LIGHT_SCHEME).toBe(COLOR_SCHEME_PALETTES.violet.light);
    expect(DARK_SCHEME).toBe(COLOR_SCHEME_PALETTES.violet.dark);
  });

  it("actually changes colour between the two schemes", () => {
    expect(DARK_SCHEME["app-surface-page"]).not.toBe(
      LIGHT_SCHEME["app-surface-page"],
    );
    expect(DARK_SCHEME["on-surface"]).not.toBe(LIGHT_SCHEME["on-surface"]);
  });

  it("keeps a card lighter than its page in BOTH schemes", () => {
    // The whole reason the `--md-app-color-*` extensions exist: one system alias
    // cannot express "the card lifts off the page" in light AND dark, because
    // light lifts toward white and dark lifts away from black.
    for (const [name, scheme] of BOTH_SCHEMES) {
      expect(
        luminance(scheme["app-surface-card"]),
        `${name}: the card must be lighter than the page`,
      ).toBeGreaterThan(luminance(scheme["app-surface-page"]));
    }
  });
});

/*
 * The application-surface system.
 *
 * PR #120 aliased all four app surfaces onto the system container ramp, which
 * `SchemeVibrant` builds at chroma 10 — so the page, every filter bar and every
 * sunken panel carried a visible lavender tint, and in dark the navigation
 * drawer and the page resolved to the same hex. These assertions pin the
 * properties that fix relied on, so neither can come back quietly.
 */
describe("the generated application surfaces", () => {
  /** Every app surface, in the order the design system stacks them. */
  const APP_SURFACES = [
    "app-surface-sunken",
    "app-surface-page",
    "app-surface-card-subtle",
    "app-surface-navigation",
    "app-surface-app-bar",
    "app-surface-card",
    "app-surface-raised",
  ] as const;

  /**
   * The chroma ceiling for an application surface, per appearance.
   *
   * LIGHT is unchanged at 6, and deliberately so: the defect this rule replaces
   * measured chroma 9.0–10.2 on every surface, and at the near-white tones a
   * light canvas uses (92–100) that is a visible lavender wash over the entire
   * product. 6 leaves real headroom under it and sits well under the ~8 at which
   * a tint becomes a colour at those tones.
   *
   * DARK is 14, and the difference is the same one the generated tint-strength
   * table already makes: there is no white to tint at tones 6–26, so the same
   * chroma that washes a light canvas reads as a deep navy or a charcoal-plum —
   * a dark NEUTRAL with a temperature, which is precisely what "Electric's shell
   * is blue-black" means. Holding dark to the light ceiling made Electric's dark
   * frame indistinguishable from Daly Violet's, which is a scheme unable to state
   * its own headline claim. 14 still refuses a surface that has become a colour:
   * the shipped values run 3.1–11.4.
   */
  const CHROMA_CEILING = { light: 6, dark: 14 } as const;

  it("keeps every application surface low-chroma, so there is no colour wash", () => {
    for (const [name, scheme] of EVERY_SCHEME) {
      const ceiling = name.endsWith("/dark")
        ? CHROMA_CEILING.dark
        : CHROMA_CEILING.light;
      for (const role of APP_SURFACES) {
        expect(
          chroma(scheme[role]),
          `${name} --md-app-color-${role.slice("app-".length)} must stay near-neutral`,
        ).toBeLessThan(ceiling);
      }
      expect(
        chroma(scheme["app-outline-hairline"]),
        `${name}: the card hairline must stay near-neutral too`,
      ).toBeLessThan(ceiling);
    }
  });

  it("keeps every LIGHT canvas under the original wash ceiling", () => {
    // Stated separately as well as inside the sweep above, because this is the
    // rule PR #120 broke and the one a future scheme is most likely to be tempted
    // to relax. A light working surface is neutral. There is no exception.
    for (const scheme of GENERATED_COLOR_SCHEMES) {
      for (const role of APP_SURFACES) {
        expect(
          chroma(COLOR_SCHEME_PALETTES[scheme].light[role]),
          `${scheme} light ${role}`,
        ).toBeLessThan(6);
      }
    }
  });

  it("keeps every application surface COOL rather than lilac", () => {
    // The seed's HCT hue is 295°, on the magenta side of blue, so simply
    // lowering the chroma of M3's own neutral ramp yields a faint lilac. The
    // generator rotates the app-neutral hue to the cool end; blue never being
    // below red is the cheap, unambiguous statement of that.
    for (const [name, scheme] of EVERY_SCHEME) {
      for (const role of APP_SURFACES) {
        const [r, , b] = rgb(scheme[role]);
        expect(
          b,
          `${name} --md-app-color-${role.slice("app-".length)} (${scheme[role]}) must not be warmer than neutral`,
        ).toBeGreaterThanOrEqual(r);
      }
    }
  });

  it("separates navigation and the app bar from the page", () => {
    // Asserted in TONE, not in relative luminance. Luminance is not
    // perceptually uniform: the same visible step is worth ~0.02 at the light
    // end and ~0.002 at the dark end, so one luminance threshold cannot describe
    // both schemes. Tone is L*, which is uniform by construction.
    //
    // 1.4 is the floor because the separation here is deliberately quiet — the
    // reference puts a white drawer on a tone-97.5 canvas — and the shell draws
    // the app-neutral hairline where the boundary has to be unambiguous. What
    // this rules out is the PR #120 state, where dark navigation and the dark
    // page were the SAME hex and the step was zero.
    for (const [name, scheme] of EVERY_SCHEME) {
      const page = tone(scheme["app-surface-page"]);
      for (const role of [
        "app-surface-navigation",
        "app-surface-app-bar",
      ] as const) {
        expect(
          Math.abs(tone(scheme[role]) - page),
          `${name}: ${role} (${scheme[role]}) must be tonally distinct from the page (${scheme["app-surface-page"]})`,
        ).toBeGreaterThanOrEqual(1.4);
      }
    }
  });

  it("keeps sunken recessed and card-subtle below the card", () => {
    // Both schemes recede DOWNWARD — a well is darker than what surrounds it in
    // light and in dark alike. The page is already near black in dark, which is
    // exactly why sunken needs its own rung below it rather than an alias.
    for (const [name, scheme] of EVERY_SCHEME) {
      expect(
        tone(scheme["app-surface-sunken"]),
        `${name}: sunken must be recessed below the page`,
      ).toBeLessThan(tone(scheme["app-surface-page"]));
      expect(
        tone(scheme["app-surface-card-subtle"]),
        `${name}: card-subtle must sit below the card`,
      ).toBeLessThan(tone(scheme["app-surface-card"]));
    }
  });

  it("keeps a raised surface at or above the card, and above it in dark", () => {
    // In LIGHT a raised surface is separated by ELEVATION, not by tone: tinting
    // it darker than the card is exactly what made PR #120's Today hero read as
    // sunken on the product's most-visited screen. In DARK shadow barely reads
    // against a near-black page, so raised steps up the ramp instead.
    for (const scheme of GENERATED_COLOR_SCHEMES) {
      const light = COLOR_SCHEME_PALETTES[scheme].light;
      const dark = COLOR_SCHEME_PALETTES[scheme].dark;
      expect(
        tone(light["app-surface-raised"]),
        `${scheme} light: raised must never be darker than a card`,
      ).toBeGreaterThanOrEqual(tone(light["app-surface-card"]));
      expect(
        tone(dark["app-surface-raised"]) - tone(dark["app-surface-card"]),
        `${scheme} dark: raised must lift clearly off the card`,
      ).toBeGreaterThanOrEqual(4);
    }
  });
});

describe("M3-01 required tokens", () => {
  const defined = allDefinedTokenNames();

  it("defines every required token (colour and structural)", () => {
    for (const name of REQUIRED_TOKEN_NAMES) {
      expect(defined.has(name), `missing token --${name}`).toBe(true);
    }
  });

  it("keeps breakpoint tokens in sync with the TS scale", () => {
    const tokens = allTokens();
    const remToPx = (rem: string) => Math.round(parseFloat(rem) * 16);
    expect(remToPx(tokens.get("app-breakpoint-sm")!)).toBe(BREAKPOINTS.sm);
    expect(remToPx(tokens.get("app-breakpoint-md")!)).toBe(BREAKPOINTS.md);
    expect(remToPx(tokens.get("app-breakpoint-lg")!)).toBe(BREAKPOINTS.lg);
    expect(remToPx(tokens.get("app-breakpoint-xl")!)).toBe(BREAKPOINTS.xl);
    expect(remToPx(tokens.get("app-breakpoint-2xl")!)).toBe(BREAKPOINTS["2xl"]);
  });
});

describe("M3-01 the alias layer is gone", () => {
  const tokens = allTokens();

  it("defines no `--dh-` token at all", () => {
    // The alias layer existed so the switch to M3 could be one commit rather
    // than sixty. Its exit criterion was always explicit: when nothing under
    // `app/` reads a `--dh-` name, the block goes. This is that zero, guarded.
    const survivors = [...tokens.keys()].filter((name) =>
      name.startsWith("dh-"),
    );
    expect(
      survivors,
      `the alias layer is retired; these definitions should have gone with it: ${survivors.join(", ")}`,
    ).toEqual([]);
  });

  it("leaves no `--dh-` reference anywhere under app/", () => {
    const offenders: string[] = [];
    for (const file of appSourceFiles()) {
      const text = readAppFile(appRelative(file));
      if (text.includes("--dh-")) offenders.push(repoRelative(file));
    }
    expect(
      offenders,
      `these files still speak the retired vocabulary: ${offenders.join(", ")}`,
    ).toEqual([]);
  });

  it("renamed every structural survivor to `--app-`", () => {
    // Spacing, z-index, breakpoints and the shell's measurements are not design
    // language — M3 neither supplies nor constrains them — so they survived the
    // overhaul under a prefix that says what they are.
    for (const name of LEGACY_STRUCTURAL_TOKEN_NAMES) {
      expect(tokens.has(name), `missing --${name}`).toBe(true);
    }
  });
});

describe("M3-01 no consumer references an undefined token", () => {
  const defined = allDefinedTokenNames();

  it("every var(--md-*) and var(--dh-*) used in app/ is defined", () => {
    const referenced = new Map<string, string>(); // token -> first file
    const re = /var\(\s*--((?:md|app)-[\w-]+)/g;
    for (const file of appSourceFiles()) {
      // The token registry itself CONSTRUCTS `var(--md-sys-color-<role>)`
      // dynamically; it is the source of truth, not a consumer.
      if (appRelative(file).startsWith("shared/tokens")) continue;
      const text = readAppFile(appRelative(file));
      let match: RegExpExecArray | null;
      while ((match = re.exec(text)) !== null) {
        if (!referenced.has(match[1])) {
          referenced.set(match[1], repoRelative(file));
        }
      }
    }

    expect(referenced.size).toBeGreaterThan(0);
    for (const [token, file] of referenced) {
      expect(
        defined.has(token),
        `undefined token --${token} used in ${file}`,
      ).toBe(true);
    }
  });
});

describe("the retired seven-theme mechanism has not come back", () => {
  it("declares no `data-theme` palette in the stylesheet", () => {
    // THEME-01 added five colour schemes and did NOT reinstate this. The
    // difference is the whole point: `data-theme` selected between seven
    // hand-authored palettes that carried their own component rules;
    // `data-color-scheme` selects between five GENERATED token maps over one
    // component system, and no module stylesheet may branch on it (asserted in
    // `appearance-cascade.test.ts`).
    expect(tokensCss).not.toContain('[data-theme="');
  });

  it("selects dark by the OS preference alone", () => {
    expect(tokensCss).toContain("@media (prefers-color-scheme: dark)");
  });

  it("honours prefers-reduced-motion in the base styles", () => {
    const baseCss = readAppFile("styles/base.css");
    expect(baseCss).toContain("@media (prefers-reduced-motion: reduce)");
    expect(baseCss).toMatch(
      /transition-duration:\s*var\(--md-sys-motion-duration-none\)/,
    );
  });
});
